/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * user guide available at https://docs.gradle.org/5.0/userguide/tutorial_java_projects.html
 */
val jackson by extra("2.14.2")
val hazelcast by extra("4.2.4")

plugins {
    // Apply the java plugin to add support for Java
    java
    idea
    jdepend
    `project-report`
 //   pmd
    // Apply the application plugin to add support for building an application
    application
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    mavenLocal()
    google()
    maven(url = "http://central.maven.org/maven2/")
    mavenCentral()
    maven(url = "https://mvnrepository.com/artifact")
    maven(url = "https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-scripting-jvm")
    maven {
        setUrl("https://repository.hazelcast.com/release")
        metadataSources {
            mavenPom()
            artifact()
        }
    }
}

dependencies {
    // This dependency is found on compile classpath of this component and consumers.

    //hz deps
    implementation("com.hazelcast:hazelcast:3.12.2")
    implementation("com.hazelcast:hazelcast-client:3.12.2")

    implementation("org.jetbrains.kotlin:kotlin-scripting-jvm:1.3.61")
	
    // remote connections
// https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient
    implementation("org.apache.httpcomponents:httpclient:4.5.6")


    compileOnly("org.projectlombok:lombok:1.18.10")
    annotationProcessor("org.projectlombok:lombok:1.18.10")

    // async library
    implementation("io.reactivex.rxjava2:rxjava:2.2.0")

    // QR code scanner
    implementation("com.google.zxing:core:3.3.0")
    implementation("com.google.zxing:javase:3.3.0")


    //json processing
    implementation("com.fasterxml.jackson.core:jackson-core:${jackson}")
    implementation("com.fasterxml.jackson.core:jackson-annotations:${jackson}")
    implementation("com.fasterxml.jackson.core:jackson-databind:${jackson}")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jdk8:${jackson}")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${jackson}")
    
    implementation("com.jayway.jsonpath:json-path:2.4.0")

    // https://mvnrepository.com/artifact/joda-time/joda-time
    implementation("joda-time:joda-time:2.10.3")


    implementation("com.google.flatbuffers:flatbuffers-java:1.11.1")
    implementation("com.google.code.gson:gson:2.8.5")

    // commons collections
    implementation("org.apache.commons:commons-collections4:4.3")
    implementation("org.apache.commons:commons-text:1.6")
    implementation("com.google.guava:guava:31.1-jre")
    implementation("org.apache.commons:commons-lang3:3.8.1")
    implementation("org.apache.commons:commons-compress:1.18")
    implementation("org.tukaani:xz:1.8")
    implementation("commons-io:commons-io:2.6")
    
    //validators
    implementation("commons-validator:commons-validator:1.7")
    
    
    // time lib
    implementation("joda-time:joda-time:2.10.1")

    
    // logging
//    implementation("org.slf4j:slf4j-api:1.7.25")
//    implementation("org.slf4j:slf4j-jdk14:1.7.25")
    implementation("org.apache.logging.log4j:log4j-core:2.12.1")
    implementation("org.apache.logging.log4j:log4j-api:2.12.1")
    implementation("org.apache.logging.log4j:log4j-slf4j-impl:2.12.1")

    //Base 64 lib
    implementation("commons-codec:commons-codec:1.11")


    // hystrix
    implementation("com.netflix.hystrix:hystrix-core:1.5.18")
    implementation("com.netflix.hystrix:hystrix-javanica:1.5.18")
    implementation("com.netflix.hystrix:hystrix-examples:1.5.18")

    // Benchmarking dependencies JMH
    // The jmh is a Java harness for building, running, and analysing nano/micro/macro benchmarks
    // written in Java and other languages targeting the JVM
    implementation("org.openjdk.jmh:jmh-parent:1.21")
    implementation("org.openjdk.jmh:jmh-generator-annprocess:1.21")
    implementation("org.openjdk.jmh:jmh-generator-bytecode:1.21")
    implementation("org.openjdk.jmh:jmh-generator-reflection:1.21")
    implementation("org.openjdk.jmh:jmh-generator-asm:1.21")
    implementation("org.openjdk.jmh:jmh-core-benchmarks:1.21")
    implementation("org.openjdk.jmh:jmh-samples:1.21")
    implementation("org.openjdk.jmh:jmh-core:1.21")

    // byte code manipulation
    implementation("org.javassist:javassist:3.24.0-GA")



    //apache camel
    implementation("org.apache.camel:camel-core:3.0.0-M2")
    testImplementation("org.apache.camel:camel-test:3.0.0-M2")
    // ref: https://docs.gradle.org/current/userguide/java_testing.html#compiling_and_executing_junit_jupiter_tests
    // Use JUnit test framework
    // JUnit 5 = JUnit Platform + JUnit Jupiter + JUnit Vintage
    // JUnit 5 is the latest version of the well-known JUnit test framework. Unlike its predecessor, JUnit 5 is modularized and composed of several modules:
    // The JUnit Platform serves as a foundation for launching testing frameworks on the JVM.
    // JUnit Jupiter is the combination of the new programming model and extension model
    // for writing tests and extensions in JUnit 5. JUnit Vintage provides a TestEngine for
    // running JUnit 3 and JUnit 4 based tests on the platform.
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.2")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.9.2")

    // If you want to run JUnit 3/4 tests on JUnit Platform,
    // or even mix them with Jupiter tests, you should add extra JUnit Vintage Engine dependencies
//    testCompile("junit:junit:4.12")
//    testRuntimeOnly("org.junit.vintage:junit-vintage-engine:5.3.2")
}


application {
    // Define the main class for the application
    mainClassName = "com.dkb.App"
}

idea {
    module {
        isDownloadJavadoc = true
        isDownloadSources = true
    }
}
